# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFuGxonvpdUsa8J43Gs-WBkM0WiJkQs6
"""

print("Hello World")